language: python
sudo: false
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

cache:
    directories:
        - $HOME/.hypothesis

env:
  global:
    - HYPOTHESIS_STORAGE_DIRECTORY=$HOME/.hypothesis

install:
  - travis_retry pip install python-coveralls nose-cov hypothesis
  - pip install .

# Run test
script:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then nosetests -v --with-cov --cov chardet --cov-config .coveragerc --logging-level=DEBUG; fi
  - if [[ $TRAVIS_PYTHON_VERSION == 'pypy' ]]; then nosetests -v --logging-level=DEBUG; fi

# Calculate coverage
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != 'pypy' ]]; then coveralls --config_file .coveragerc; fi

notifications:
  email:
    on_success: change
    on_failure: always
